torso_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - torso_1_joint
    - torso_2_joint

  constraints:
    goal_time: &goal_time_constraint 0.6
    torso_1_joint:
      goal: &goal_pos_constraint 0.02
    torso_2_joint:
      goal: *goal_pos_constraint

head_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - head_1_joint
    - head_2_joint

  constraints:
    goal_time: *goal_time_constraint
    head_1_joint:
      goal: *goal_pos_constraint
    head_2_joint:
      goal: *goal_pos_constraint

left_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
  constraints:
    goal_time: *goal_time_constraint
    arm_left_1_joint:
      goal: *goal_pos_constraint
    arm_left_2_joint:
      goal: *goal_pos_constraint
    arm_left_3_joint:
      goal: *goal_pos_constraint
    arm_left_4_joint:
      goal: *goal_pos_constraint
    arm_left_5_joint:
      goal: *goal_pos_constraint
    arm_left_6_joint:
      goal: *goal_pos_constraint
    arm_left_7_joint:
      goal: *goal_pos_constraint

right_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
  constraints:
    goal_time: *goal_time_constraint
    arm_right_1_joint:
      goal: *goal_pos_constraint
    arm_right_2_joint:
      goal: *goal_pos_constraint
    arm_right_3_joint:
      goal: *goal_pos_constraint
    arm_right_4_joint:
      goal: *goal_pos_constraint
    arm_right_5_joint:
      goal: *goal_pos_constraint
    arm_right_6_joint:
      goal: *goal_pos_constraint
    arm_right_7_joint:
      goal: *goal_pos_constraint

right_hand_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - hand_right_index_joint
    - hand_right_middle_joint
    - hand_right_thumb_joint

  constraints:
    goal_time: *goal_time_constraint
    hand_right_index_joint:
      goal: *goal_pos_constraint
    hand_right_middle_joint:
      goal: *goal_pos_constraint
    hand_right_thumb:
      goal: *goal_pos_constraint

left_hand_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - hand_left_index_joint
    - hand_left_middle_joint
    - hand_left_thumb_joint

  constraints:
    goal_time: *goal_time_constraint
    hand_left_index_joint:
      goal: *goal_pos_constraint
    hand_left_middle_joint:
      goal: *goal_pos_constraint
    hand_left_thumb:
      goal: *goal_pos_constraint
