right_arm_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &arm_right_joints
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
  gains:
    arm_right_1_joint: &arm_1_gains {p: 800, d: 500, i: 200, i_clamp: 3.0}
    arm_right_2_joint: &arm_2_gains {p: 800, d: 500, i: 200, i_clamp: 3.0}
    arm_right_3_joint: &arm_3_gains {p: 600, d: 350, i: 150, i_clamp: 2.0}
    arm_right_4_joint: &arm_4_gains {p: 800, d: 500, i: 200, i_clamp: 3.0}
    arm_right_5_joint: &arm_5_gains {p: 300, d: 300, i: 100, i_clamp: 1.5}
    arm_right_6_joint: &arm_6_gains {p: 300, d: 250, i: 100, i_clamp: 1.5}
    arm_right_7_joint: &arm_7_gains {p: 300, d: 250, i: 100, i_clamp: 1.5}
  joint_trajectory_action_node:
    joints: *arm_right_joints
    constraints:
      goal_time: &goal_time_constraint 0.6
      arm_right_1_joint:
        goal: &goal_pos_constraint 0.02
      arm_right_2_joint:
        goal: *goal_pos_constraint
      arm_right_3_joint:
        goal: *goal_pos_constraint
      arm_right_4_joint:
        goal: *goal_pos_constraint
      arm_right_5_joint:
        goal: *goal_pos_constraint
      arm_right_6_joint:
        goal: *goal_pos_constraint
      arm_right_7_joint:
        goal: *goal_pos_constraint

right_arm_torso_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &arm_right_torso_joints
    - torso_1_joint
    - torso_2_joint
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
  gains:
    torso_1_joint:    {p: 1500.0, d: 800.0, i: 300, i_clamp: 6.0}
    torso_2_joint:    {p: 1500.0, d: 800.0, i: 300, i_clamp: 6.0}
    arm_right_1_joint: *arm_1_gains
    arm_right_2_joint: *arm_2_gains
    arm_right_3_joint: *arm_3_gains
    arm_right_4_joint: *arm_4_gains
    arm_right_5_joint: *arm_5_gains
    arm_right_6_joint: *arm_6_gains
    arm_right_7_joint: *arm_7_gains
  joint_trajectory_action_node:
    joints: *arm_right_torso_joints
    constraints:
      goal_time: *goal_time_constraint
      torso_1_joint:
        goal: *goal_pos_constraint
      torso_2_joint:
        goal: *goal_pos_constraint
      arm_right_1_joint:
        goal: *goal_pos_constraint
      arm_right_2_joint:
        goal: *goal_pos_constraint
      arm_right_3_joint:
        goal: *goal_pos_constraint
      arm_right_4_joint:
        goal: *goal_pos_constraint
      arm_right_5_joint:
        goal: *goal_pos_constraint
      arm_right_6_joint:
        goal: *goal_pos_constraint
      arm_right_7_joint:
        goal: *goal_pos_constraint

left_arm_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints: &arm_left_joints
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
  gains:
    arm_left_1_joint: *arm_1_gains
    arm_left_2_joint: *arm_2_gains
    arm_left_3_joint: *arm_3_gains
    arm_left_4_joint: *arm_4_gains
    arm_left_5_joint: *arm_5_gains
    arm_left_6_joint: *arm_6_gains
    arm_left_7_joint: *arm_7_gains
  joint_trajectory_action_node:
    joints: *arm_left_joints
    constraints:
      goal_time: *goal_time_constraint
      arm_left_1_joint:
        goal: *goal_pos_constraint
      arm_left_2_joint:
        goal: *goal_pos_constraint
      arm_left_3_joint:
        goal: *goal_pos_constraint
      arm_left_4_joint:
        goal: *goal_pos_constraint
      arm_left_5_joint:
        goal: *goal_pos_constraint
      arm_left_6_joint:
        goal: *goal_pos_constraint
      arm_left_7_joint:
        goal: *goal_pos_constraint
